### ISSUE TITLE
5000 images with images of each emotions 

### ISSUE THREAD

**Issue by hajungong007** [athulsn/Emotion-Detection#1]
hi， where can I download  5000 images with images of each emotions? Thanks

**Comment by shamilam** [comment]
Hi,
You can use CK (Cohn-Kanade) database which is available online.

**Comment by shamilam** [comment]
http://www.consortium.ri.cmu.edu/ckagree
Visit this link, enter your details and submit. You'll receive an email with the required ID and password to be entered while visiting the specified URL.

**Comment by hajungong007** [comment]
thanks！
