### ISSUE TITLE
cannot run train.exe on the csv

### ISSUE THREAD

**Issue by antithing** [athulsn/Emotion-Detection#2]
Hi, thank you for this code, I am trying to get it to work, and am stuck. I run the annotate on a happy set, and create the csv.

I am trying to get the train.exe to run on the file, but I get:

`matrix.size(): 120
matrixLab.size(): 120
Happy: 120
Sad  : 0
samples.size(): 120
labels.size() : 120
exception thrown!
Invalid nu of 0.0498789.  It is required that: 0 < nu < 0
Press any key to continue . . .`

in this section:

```
           `trainer.set_kernel(kernel_type(1.4641e-05));
    trainer.set_nu(0.0498789);
    typedef probabilistic_decision_function<kernel_type> probabilistic_funct_type;
    typedef normalized_function<probabilistic_funct_type> pfunct_type;

    pfunct_type learned_pfunct;
    learned_pfunct.normalizer = normalizer;
    learned_pfunct.function = train_probabilistic_decision_function(trainer, samples, labels, 3); //this line causes exception`
```

Could you please assist me in what could be going wrong?

Thank you!

**Comment by athulsnambiar** [comment]
This program needs at least two emotions to classify. You cannot classify happy images alone. Since train.exe was made for binary classification it needs two sets of images(Happy and sad).

**Comment by antithing** [comment]
Ah, I see. got it. Thank you! I have a couple more questions, if you have a minute.

Can I just add more emotions to the csv? eg: annotate.exe 6 eyes_open ?

To train with all emotions, do I just run train.exe two at a time, and it will append the emotion_predictor_data file? Or do i need to adjust the code to take more than 2 emotions at once?

Thank you again for your time.

**Comment by athulsnambiar** [comment]
To Classify emotions
Step 1:

Just run annotate.exe 4 times.
In the program, we have hard coded 4 emotion types and each has a number.

So run annotate.exe like this.

./annotate.exe 0 ./locaton/to/neutral/images/_.jpg
./annotate.exe 2 ./locaton/to/happy/images/_.jpg
./annotate.exe 3 ./locaton/to/sad/images/_.jpg
./annotate.exe 4 ./locaton/to/surprise/images/_.jpg

There is no anger emotion.......

Step 2:
Train SVM with the features
for this run any of the following

./train4ClassProbablityOVA.exe

or

./train4ClassProbablityOVO.exe

One is for "One vs All" Classification and other is for "One vs One" Classification

Step 3:
Classifying images
For this run one of the following according to what training you gave in last step

./emotionRecognition4ClassProbablityOVA.exe ./location/to/image/imagename.jpg

or

./emotionRecognition4ClassProbablityOVO.exe ./location/to/image/imagename.jpg

Thats it!!!
